notifications:
  email: false
language: python
cache: pip
python:
  - "2.7"
dist: xenial
services:
  - xvfb
before_install:
  - sudo apt-get install python-gtk2
  - sudo apt-get install libgtkglext1
  - sudo apt-get install python-pip
  - sudo apt-get install imagemagick
  - sudo apt-get install libgtk2.0-dev
  - sudo apt-get install libgirepository1.0-dev
  - sudo apt-get install libgtkglext1-dev
  - sudo apt-get install mesa-utils
  - sudo apt-get install openimageio-tools
  #- sudo apt-get libgbm1
  - sudo apt-get libgl1-mesa-dri
  - sudo chmod +x ./screenshot.sh
install:
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
  - pip install --upgrade pip
  - pip install setuptools --no-python-version-warning
  - pip install --install-option="--prefix=${VIRT_ROOT}" freetype-py --no-python-version-warning
  - pip install --install-option="--prefix=${VIRT_ROOT}" typing --no-python-version-warning
  - pip install --install-option="--prefix=${VIRT_ROOT}" pycairo --no-python-version-warning
  - pip install --install-option="--prefix=${VIRT_ROOT}" PyOpenGL --no-python-version-warning
  # PyGobject
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
  - tar xf pygobject-2.28.6.tar.bz2
  - cd pygobject-2.28.6
  - ./configure --prefix=$VIRT_ROOT --disable-introspection
  - make > /dev/null
  - make install > /dev/null
  - cd ..
  # PyGtk
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0
  - ./configure --prefix=$VIRT_ROOT
  - make /dev/null
  - make install > /dev/null
  - cd ..
  # gtkglext
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python-gtkglext1/python-gtkglext1_1.1.0.orig.tar.gz
  - tar -xzf python-gtkglext1_1.1.0.orig.tar.gz
  - cd python-gtkglext1-1.1.0
  - ./configure --prefix=${VIRT_ROOT}
  - make /dev/null
  - make install > /dev/null
  - cd ..
script:
  - top -n 1
  - sudo pkill Xvfb
  - xvfb-run glxinfo
  - xvfb-run python -B test.py || true
  - xvfb-run ./screenshot.sh playground.png || true
