language: python
python:
  - "2.7"
install:
  - pip install setuptools
  - pip install freetype-py
  - pip install typing
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0
  - export PKG_CONFIG_PATH=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/pkgconfig
  - ./configure --prefix=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/
  - make
  - make install
script:
  python -B test.py
  