language: python
python:
  - "2.7"
before_install:
  - ./install-deps.sh
install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install freetype-py
  - pip install typing
script:
  python -B test.py
  