language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-gtk2
  - sudo apt-get install libgtkglext1
  #- sudo apt-get install python-opengl
  - sudo apt-get install python-gtkglext1
  - sudo apt-get install python-pip
  - sudo apt-get install imagemagick
  - sudo apt-get install libgtk2.0-dev
  - sudo apt-get install libgirepository1.0-dev
install:
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
  - pip install --upgrade pip
  - pip install setuptools
  - pip install --install-option="--prefix=${VIRT_ROOT}" freetype-py
  - pip install --install-option="--prefix=${VIRT_ROOT}" typing
  - pip install --install-option="--prefix=${VIRT_ROOT}" pygobject
  - pip install --install-option="--prefix=${VIRT_ROOT}" pycairo
  - pip install --install-option="--prefix=${VIRT_ROOT}" PyOpenGL
  # PyCairo
  #- wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2
  #- tar xf py2cairo-1.10.0.tar.bz2
  #- cd py2cairo-1.10.0
  #- ./waf configure --prefix=${VIRT_ROOT}
  #- ./waf build
  #- ./waf install
  #- cd ..
  # PyGobject
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
  - tar xf pygobject-2.28.6.tar.bz2
  - cd pygobject-2.28.6
  - ./configure --prefix=$VIRT_ROOT --disable-introspection
  - make
  - make install > /dev/null
  - cd ..
  # PyGtk
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0
  - ./configure --prefix=$VIRT_ROOT
  - make
  - make install > /dev/null
  - cd ..
  # gtkglext
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/p/python-gtkglext1/python-gtkglext1_1.1.0.orig.tar.gz
  - tar -xzf python-gtkglext1_1.1.0.orig.tar.gz
  - cd python-gtkglext1-1.1.0
  - ./configure --prefix=${VIRT_ROOT}
  - make
  - make install > /dev/null
  - cd ..
script:
  - python -B test.py
