language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-gtk2
  - sudo apt-get install libgtkglext1
  - sudo apt-get install python-opengl
  - sudo apt-get install python-gtkglext1
  - sudo apt-get install python-pip
install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install freetype-py
  - pip install typing
script:
  - python2 -B test.py
