language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python-gtk2
  - sudo apt-get install libgtkglext1
  - sudo apt-get install python-opengl
  - sudo apt-get install python-gtkglext1
  - sudo apt-get install python-pip
  - sudo apt-get install imagemagick
  - sudo apt-get install python-gobject-2-dev
install:
  - pip install --upgrade pip
  - pip install setuptools
  - pip install freetype-py
  - pip install typing
  # PyGtk
  - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  - tar xf pygtk-2.24.0.tar.bz2
  - cd pygtk-2.24.0
  - echo "VIRT_ROOT:\"${VIRT_ROOT}\""
  - ./configure --prefix=$VIRT_ROOT
  - make
  - make install
  - cd ..
script:
  - python -B test.py
